#!/bin/bash

#####################################################################################################################
#                                                                                                                   #
#                     This script is written by Pierre aka Linoge, admin of Webbh4tt                                #
#  This program is open source; you can redistribute it and/or modify it under the terms of the GNU General Public  #
#                 The author bears no responsibility  for malicious or illegal use.                                 #
#                                                                                                                   #
#                                                                                                                   #
#####################################################################################################################

# ~~~~~~~~~~  Environment Setup ~~~~~~~~~~ #
    NORMAL=`echo "\033[m"`
    MENU=`echo "\033[36m"` #Blue
    NUMBER=`echo "\033[33m"` #yellow
    FGRED=`echo "\033[41m"`
    RED_TEXT=`echo "\033[31m"` #Red
    ENTER_LINE=`echo "\033[33m"`
    INTRO_TEXT=`echo "\033[32m"` #green and white text
    INFOS=`echo "\033[103;30m"` #yellow bg
    SUCCESS=`echo "\033[102;30m"` #green bg
    WARNING=`echo "\033[101;30m"` #red bg
    WARP=`echo "\033[106;30m"` #lightblue bg
    BLACK=`echo "\033[109;30m"` #SPACE bg
    END=`echo "\033[0m"`
# ~~~~~~~~~~  Environment Setup ~~~~~~~~~~ #

if [ ! -x /etc/bind ];then
echo -e "$warn\nNeed to install Bind9"
  sleep 1
  echo "$q\nDo you want to do it now? (y/n)"
  read var
    if [ $var = y ];then
    sudo apt-get install bind9 -y
    else
    exit;
    fi
fi
echo "${MENU}$q\nDo you whan to set DNS-servername to localhost in the network interfaces ( recomended! )? (y/n)${END}"
read vir
if [ $vir = y ];then
sudo echo "dns-nameservers 127.0.0.1" >> /etc/network/interfaces
fi


echo "${MENU}$q\nDo you whan to set forwarders to google DNS ( recomended! )? (y/n)${END}"
read ver
if [ $ver = y ];then
sudo cp /etc/bind/named.conf.options /etc/bind/named.conf.options.backup
echo "options {
        directory \"/var/cache/bind\";

        // If there is a firewall between you and nameservers you want
        // to talk to, you may need to fix the firewall to allow multiple
        // ports to talk.  See http://www.kb.cert.org/vuls/id/800113

        // If your ISP provided one or more IP addresses for stable
        // nameservers, you probably want to use them as forwarders.
        // Uncomment the following block, and insert the addresses replacing
        // the all-0's placeholder.

         forwarders {
                8.8.8.8;
                8.8.4.4;
         };

        //========================================================================
        // If BIND logs error messages about the root key being expired,
        // you will need to update your keys.  See https://www.isc.org/bind-keys
        //========================================================================
        dnssec-validation auto;

        auth-nxdomain no;    # conform to RFC1035
        listen-on-v6 { any; };
};" > /etc/bind/named.conf.options
fi
sudo cp /etc/bind/named.conf.local /etc/bind/named.conf.local.backup
echo "${MENU}Please type in you dns name ( like... iamcool.com )${END}"
read Site
echo "zone \"$Site\" {
        type master;
        file \"/etc/bind/db.$Site\";
};" >> /etc/bind/named.conf.local
echo "${MENU}Please type in the ip adress for your dns name ( like... 192.168.1.3  = iamcool.com )${END}"
read Ip
sudo cp /etc/bind/db.empty /etc/bind/db.$Site
sudo echo "; BIND reverse data file for empty rfc1918 zone
;
; DO NOT EDIT THIS FILE - it is used for multiple zones.
; Instead, copy it, edit named.conf, and use that copy.
;
\$TTL    86400
@       IN      SOA     $Site. root.localhost. (
                              1         ; Serial
                         604800         ; Refresh
                          86400         ; Retry
                        2419200         ; Expire
                          86400 )       ; Negative Cache TTL
;
        IN      A       $Ip
@       IN      NS      localhost." > /etc/bind/db.$Site
sudo service bind9 restart
echo "${SUCCESS}All done!${END}"